name: Check & Merge Prompt

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get base commit SHA
      id: base_sha
      run: |
        # 使用git log命令获取前一次提交的哈希值
        BEFORE_COMMIT=$(git log -n 1 --skip 1 --pretty=format:"%H")
        echo "::set-output name=base_sha::$BEFORE_COMMIT"

    - name: Get changed files
      id: get_files
      run: |
        BASE_SHA="${{ steps.base_sha.outputs.base_sha }}"
        CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD)
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Run validation script
      run: |
        CHANGED_FILES="${{ steps.get_files.outputs.files }}"
        for file in $CHANGED_FILES; do
          if [[ $file == *.md ]]; then
            python validate_script.py "$file"
          fi
        done
  prompt_to_json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 检出完整的提交历史

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # 指定所需的 Python 版本

    - name: gpt_prompt to json
      env:
        folder_path: 'test/prompt/gpt_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: yiyan_prompt to json
      env:
        folder_path: 'test/prompt/yiyan_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: Merge the gpt_prompt
      run: python .ci/build_all_gpt_prompt.py 

    - name: Merge the yiyan_prompt
      run: python .ci/build_all_yiyan_prompt.py 

