name: Check & Merge Prompt

on:
  pull_request_target:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 检出完整的提交历史

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: check the prompt
      run: |
        python .ci/check.py

    - name: gpt_prompt to json
      env:
        folder_path: 'test/prompt/gpt_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: yiyan_prompt to json
      env:
        folder_path: 'test/prompt/yiyan_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: upload json
      uses: actions/upload-artifact@v2
      with:
        name: upload_json
        path: tianji/prompt

    - name: Merge the gpt_prompt
      env:
        gpt_folder_path: 'tianji/prompt/gpt_prompt'
        gpt_output_json_path: 'tianji/prompt/gpt_prompt/all_gpt_prompt.json'
      run: python .ci/build_all_gpt_prompt.py

    - name: upload all gpt json
      uses: actions/upload-artifact@v2
      with:
        name: upload_all_gpt_json
        path: tianji/prompt/gpt_prompt/all_gpt_prompt.json

    - name: Merge the yiyan_prompt
      env:
        yiyan_folder_path: 'tianji/prompt/yiyan_prompt'
        yiyan_output_json_path: 'tianji/prompt/yiyan_prompt/all_yiyan_prompt.json'
      run: python .ci/build_all_yiyan_prompt.py

    - name: upload all yiyan json
      uses: actions/upload-artifact@v2
      with:
        name: upload_all_yiyan_json
        path: tianji/prompt/yiyan_prompt/all_yiyan_prompt.json

    - name: Install matplotlib
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Count the number of gpt prompts
      env:
        all_gpt_json: 'tianji/prompt/gpt_prompt/all_gpt_prompt.json'
      run : python .ci/gpt_prompt_stat.py
            mv gpt_prompt_statistics.png .ci/gpt_prompt_statistics.png

    - name: upload gpt png
      uses: actions/upload-artifact@v2
      with:
           name: gpt_prompt_statistics  # 工件的名称，您可以根据需要命名
           path: .ci/gpt_prompt_statistics.png  # 指定生成的 PNG 文件的路径

    - name: Count the number of yiyan prompts
      env:
        all_yiyan_json: 'tianji/prompt/yiyan_prompt/all_yiyan_prompt.json'
      run : python .ci/yiyan_prompt_stat.py
            mv yiyan_prompt_statistics.png .ci/yiyan_prompt_statistics.png


    - name: upload yiyan png
      uses: actions/upload-artifact@v2
      with:
        name: yiyan_prompt_statistics  # 工件的名称，您可以根据需要命名
        path: .ci/yiyan_prompt_statistics.png  # 指定生成的 PNG 文件的路径

    - name: Commit and Push Changes
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git add .  # 添加修改的文件，路径根据实际情况调整
        git commit -m "Update prompt files"  # 提交更改，自定义提交消息
        git push origin main  # 推送更改回仓库，分支名根据实际情况调整
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

