name: Check & Merge Prompt

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 检出完整的提交历史

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # 指定所需的 Python 版本

    - name: Find modified markdown files
      run: |
        # 检查是否是新分支或首次提交
        if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            # 新分支或首次提交，检查所有 .md 文件
            MD_FILES=$(git ls-files '*.md')
        else
            # 不是新分支，获取自上次提交以来修改的 .md 文件
            MD_FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep '\.md$')
        fi
        # 打印文件路径
        echo "Modified markdown files:"
        echo $MD_FILES
        # 对找到的每个 .md 文件执行后续操作
        for mdfile in $MD_FILES; do
          echo "Processing file $mdfile"
          python .ci/check_markdown.py "$mdfile" || exit 1
          
    - name: gpt_prompt to json
      env:
        folder_path: 'test/prompt/gpt_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: yiyan_prompt to json
      env:
        folder_path: 'test/prompt/yiyan_prompt'
        output_path: 'tianji/prompt'
      run: python .ci/prompt_to_json_for_CI.py

    - name: Merge the gpt_prompt
      run: python .ci/build_all_gpt_prompt.py 

    - name: Merge the yiyan_prompt
      run: python .ci/build_all_yiyan_prompt.py 

